In [16]:
import pandas as pd
import numpy as np
import xgboost as xgb

In [17]:
# Import the data

df_full = pd.read_csv("/Users/parinazfathi/Documents/GitHub/ErdosFall2024ProteinProfiles/Combined_df2.csv")

proteins=df_full.columns[4:]

In [18]:
# Encode the cancer types as numbers

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df_full['Cancer'] = le.fit_transform(df_full['Cancer'])
#df_full.head(15)

In [19]:
# Split the data into X and y
X = df_full[proteins]
y = df_full['Cancer']

In [20]:
# Split data into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100)

# Random states tested: 313, 100, 892, 276

In [21]:
# Create the xgboost model

model = xgb.XGBClassifier()

In [22]:
# Train the xgboost model

model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [23]:
# Use the model to make predictions

y_predict = model.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [25]:
accuracy = accuracy_score(y_test, y_predict)
print("Accuracy:", accuracy)

Accuracy: 0.5979020979020979


In [26]:
print("Classification Report:\n", classification_report(y_test, y_predict, target_names=le.classes_))

Classification Report:
               precision    recall  f1-score   support

         AML       0.85      0.58      0.69        19
         BRC       0.40      0.34      0.37        47
         CLL       0.78      0.54      0.64        13
         CRC       0.46      0.46      0.46        71
         CVX       0.24      0.30      0.27        27
        Ctrl       1.00      1.00      1.00        47
        ENDC       0.47      0.27      0.34        30
         ESO       1.00      1.00      1.00        34
       GLIOM       0.59      0.60      0.59        50
        HODG       1.00      1.00      1.00        52
       LUNGC       0.49      0.59      0.54        75
       LYMPH       0.56      0.31      0.40        16
        MYEL       0.55      0.60      0.57        10
         OVC       0.44      0.50      0.47        34
         PRC       0.42      0.51      0.46        47

    accuracy                           0.60       572
   macro avg       0.62      0.57      0.59       572
we

In [27]:
# Print Confusion matrix
print("Confusion Matrix:\n",confusion_matrix(y_test, y_predict))

Confusion Matrix:
 [[11  0  1  0  0  0  0  0  0  0  1  1  1  2  2]
 [ 0 16  0 11  2  0  1  0  3  0  5  0  0  2  7]
 [ 1  0  7  1  0  0  0  0  0  0  0  0  0  1  3]
 [ 0  9  0 33  2  0  2  0  0  0 15  0  1  3  6]
 [ 0  4  0  3  8  0  0  0  6  0  2  0  0  3  1]
 [ 0  0  0  0  0 47  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  2  8  0  8  0  2  0  4  1  0  1  2]
 [ 0  0  0  0  0  0  0 34  0  0  0  0  0  0  0]
 [ 0  1  0  1  7  0  2  0 30  0  1  1  0  1  6]
 [ 0  0  0  0  0  0  0  0  0 52  0  0  0  0  0]
 [ 1  3  0  9  2  0  0  0  3  0 44  0  2  7  4]
 [ 0  0  1  3  2  0  0  0  2  0  1  5  0  1  1]
 [ 0  0  0  3  0  0  0  0  0  0  0  0  6  0  1]
 [ 0  0  0  4  2  0  2  0  2  0  6  1  0 17  0]
 [ 0  5  0  1  0  0  2  0  3  0 10  0  1  1 24]]
